# Generated by Django 5.0.4 on 2025-05-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="is_send_deadline",
            field=models.BooleanField(default=False),
        ),
    ]
